# LTXV Full Model Fine-tuning Configuration

# Model configuration
model:
  model_source: "LTXV_2B_0.9.6_DEV" # Options: "LTXV_13B_097_DEV", "LTXV_2B_0.9.6_DEV", "LTXV_2B_0.9.5", "LTXV_2B_0.9.1", "LTXV_2B_0.9.0", or a HF repo/local path
  training_mode: "full" # Options: "lora" or "full"
  load_checkpoint: null # Path to checkpoint file or directory to resume from. If directory, latest checkpoint will be used.

# Optimization configuration
optimization:
  learning_rate: 1e-5 # Lower learning rate for full fine-tuning
  steps: 1000
  batch_size: 1
  gradient_accumulation_steps: 4
  max_grad_norm: 1.0
  optimizer_type: "adamw" # Use 8-bit optimizer to save memory
  scheduler_type: "linear" # Options: "constant", "linear", "cosine", "cosine_with_restarts", "polynomial"
  scheduler_params: {}
  enable_gradient_checkpointing: false # Enable to save memory
  first_frame_conditioning_p: 0.1

# Acceleration optimization
acceleration:
  mixed_precision_mode: "bf16" # Options: "no", "fp16", "bf16"
  quantization: null # Disable quantization for full fine-tuning
  load_text_encoder_in_8bit: true # Load text encoder in 8-bit precision to save memory
  compile_with_inductor: true
  compilation_mode: "reduce-overhead" # Options: "default", "reduce-overhead", "max-autotune"

# Data configuration
data:
  preprocessed_data_root: "/path/to/preprocessed/data"
  num_dataloader_workers: 2

# Validation configuration
validation:
  prompts:
    - "a professional portrait video of a person with blurry bokeh background"
    - "a video of a person wearing a nice suit"
  negative_prompt: "worst quality, inconsistent motion, blurry, jittery, distorted"
  images: null # Set to a list of image paths to use first-frame conditioning, or null to disable
  video_dims: [768, 448, 89] # [width, height, frames]
  seed: 42
  inference_steps: 50
  interval: 200 # Set to null to disable validation
  videos_per_prompt: 1
  guidance_scale: 3.5

# Checkpoint configuration
checkpoints:
  interval: 500 # Save a checkpoint every N steps, set to null to disable
  keep_last_n: -1 # Keep only the N most recent checkpoints, set to -1 to keep all

# Flow matching configuration
flow_matching:
  timestep_sampling_mode: "shifted_logit_normal" # Options: "uniform", "shifted_logit_normal"
  timestep_sampling_params: {}

# General configuration
seed: 42
output_dir: "outputs/ltxv_full_finetune"
