model:
  model_source: "LTXV_13B_097_DEV_FP8"
  training_mode: "lora"
  load_checkpoint: null
  blocks_to_swap: 0
lora:
  rank: 128
  alpha: 128
  dropout: 0.0
  target_modules:
  - "to_k"
  - "to_q"
  - "to_v"
  - "to_out.0"
optimization:
  learning_rate: 0.0002
  steps: 2000
  batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer_type: "adamw"
  scheduler_type: "linear"
  scheduler_params: {}
  enable_gradient_checkpointing: true
  first_frame_conditioning_p: 0.5
acceleration:
  mixed_precision_mode: "bf16"
  quantization: "int8-quanto"
  load_text_encoder_in_8bit: true
  compile_with_inductor: false
  compilation_mode: "reduce-overhead"
data:
  preprocessed_data_root: "workspace/datasets/CAKE/preprocessed_data"
  num_dataloader_workers: 2
validation:
  prompts:
  - "CAKEIFY a person using a knife to cut a cake shaped like bottle of mouthwash"
  - "CAKEIFY a person using a knife to cut a cake shaped like potted plant"
  - "CAKEIFY a person using a knife to cut a cake shaped like a jar of Nutella"
  negative_prompt: "worst quality, inconsistent motion, blurry, jittery, distorted"
  video_dims:
  - 512
  - 512
  - 49
  seed: 42
  inference_steps: 25
  interval: 250
  videos_per_prompt: 1
  guidance_scale: 3.5
checkpoints:
  interval: 250
  keep_last_n: -1
flow_matching:
  timestep_sampling_mode: "shifted_logit_normal"
  timestep_sampling_params: {}
seed: 42
output_dir: "workspace/output/cakeify_lora_13b"
misc:
  sampling_enabled: true
  match_enabled: true
